### ISSUE TITLE
可不可以给箭头伸缩或者单边旋转也添加自动吸附功能？

### ISSUE THREAD

**Issue by 1L2018** [tuntun0609/leafer-x-snap#16]
当使用`@leafer-in/arrow`这个包的时候，虽然拖动时可以出现自动吸附线，但是点击箭头一端伸缩旋转到另一个图形上的时候没有自动吸附线出现，这导致不能很好的链接两个图像。现在查到的解决办法可以用：https://www.leaferjs.com/ui/reference/event/basic/Property.html，    当rotate/width属性变化时触发吸附线。

**Comment by tuntun0609** [comment]
可以的，缩放或者拖拽大小时也吸附已经在计划中了
