### ISSUE TITLE
选择多个元素拖动的时候会出现问题

### ISSUE THREAD

**Issue by FZliweiliang** [tuntun0609/leafer-x-snap#8]
emit RangeError: Maximum call stack size exceeded

**Comment by tuntun0609** [comment]
是不是同屏元素太多了，有 demo 嘛

**Comment by Ctrl30** [comment]
只要简单的两个rect 把他们多选 然后移动到画布中心点就很容易复现

> 是不是同屏元素太多了，有 demo 嘛

**Comment by tuntun0609** [comment]
> emit RangeError: Maximum call stack size exceeded

把 leafer 升级成 1.0.10 试试

**Comment by Ctrl30** [comment]
复现地址
https://stackblitz.com/edit/react-j4ckjr?file=demo.tsx,index.tsx

**Comment by tuntun0609** [comment]
1.0.4 已修复，可以安装试一下，如果正常的话就可以关闭 issue 了
